--- #YAML:1.0
name:               Tree-Builder
version:            0.1
abstract:           Build Classes from a Tree Definition File
author:
    - Bill Hails <me@billhails.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Template:  2.20
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
